#!/bin/sh
# Luje
# © 2013 David Given
# This file is redistributable under the terms of the
# New BSD License. Please see the COPYING file in the
# project root for the full text.

export LUA_CPATH='/usr/lib/'$(gcc -dumpmachine)'/lua/5.1/?.so;;'
export LUA_PATH='/usr/share/lua/5.1/?.lua;;'

# If you want to use a different LuaJIT, change it here.

#luajit=/home/dg/src/luajit-2.0/src/luajit
luajit=luajit

exec $luajit vm/main.lua "$@"

